# Numpy (Arrays)
## Wofür brauchen wir Numpy?

Numpy ist eine Sammlung von Funktionen für effiziente Erzeugung, Berechnung und Bearbeitung von Zahlenstrukturen, zum Beispiel Vektoren oder Matrizen. &#x20;Wir werden Numpy nutzen, um die Datensätze für maschinelles Lernen zu bearbeiten. Eine umfangreiche, langsame Einführung finden sie unter [https://www.w3schools.com/python/numpy/](https://www.w3schools.com/python/numpy/). Wir besprechen in diesem Abschnitt nur die für unseren Inhalte relevanten Teile.

**Wichtig:** Beginnen Sie jeden Programmblock, in dem sie numpy-Funktionen brauchen, mit der Zeile

`import numpy as np`

## Vektor mit Numpy

Folgende Code zeigt, wie der ersten Feature-Vektor aus Iris 
$$
x = (5.1, 3.5, 1.4, 0.2) \in \mathbb{R}^4
$$

in einer Variable mit dem Namen `x` erzeugt wird. Wir werden sehen, dass wir aus der Mathematik gewohnten Umgang  mit Vektoren (und Matrizen) einfach in  Numpy übertragen können.

### Beispiel
```{python, results="hide"}
import numpy as np
x = np.array( [5.1, 3.5, 1.4, 0.2]) 
print( x)
print( type(x) )
```
Ausgabe: Wir sehen die Darstellung des Vektors, strukturiert über eckige Klammern und den neuen Datentyp `numpy.ndarray`.
```{python, echo=FALSE}
import numpy as np
x = np.array( [5.1, 3.5, 1.4, 0.2]) 
print( x)
print( type(x))
```

### Shape (Dimension)

Das Attribut `shape` liefert die Dimension eines Arrays.

```{python, results="hide"}
import numpy as np
x0 = np.array( [5.1, 3.5, 1.4, 0.2]) 
print( x0.shape )
```
Die Ausgabe `(4,)` bedeutet, dass die Struktur aus 4 Zahlen besteht. (Das wird im nachfolgenden Abschnitt spannender.)
```{python, echo=FALSE}
import numpy as np
f0 = np.array( [5.1, 3.5, 1.4, 0.2]) 
print( f0.shape )
```
### Zugriff auf Elemente
Für einen Vektor $\bf{x} \in \mathbb{R}^n$ nehmen wir auf die einzelnen Werte  mittels $x = (x_1, ..., x_n)$ durch Verwendung eines tiefgestellten Index  Bezug. Für  $\mathbf{x} = (5.1, 3.5, 1.4, 0.2) \in \mathbb{R}^4$ ist also $x_1 = 5.1$. In Numpy machen wir das analog, **starten die Nummerierung jedoch bei Null**, wie folgendes Beispiel zeigt. Beachten sie, dass der Index nicht tiefgestellt wird (das geht auf der Tastatur nicht so gut), sondern in eckigen Klammern nach dem Variablennamen steht.

```{python, results="hide"}
import numpy as np
x = np.array( [5.1, 3.5, 1.4, 0.2]) 
print( x[0] )
```
Ausgabe:
```{python, echo=FALSE}
import numpy as np
x = np.array( [5.1, 3.5, 1.4, 0.2]) 
print( x[0] )
```

Auf den letzten Eintrag von $x$ greifen wir mit `x[3]` zu, obwohl es der vierte  Werte ist. (Übung!)

### Werte verändern

Mit der Verwendung des Index können wir einzelne Einträge auch verändern. Wir sehen behandeln dazu den Ausdruck x[0] einfach als Variable und verwenden eine Wertzuweisung.

```{python, results="hide"}
import numpy as np
x = np.array( [5.1, 3.5, 1.4, 0.2]) 
x[0] = -3
print(x)
```
Ausgabe:
```{python, echo=FALSE}
import numpy as np
x = np.array( [5.1, 3.5, 1.4, 0.2]) 
x[0] = -3
print(x)
```
### Skalare Multiplikation und Addition

```{python, results="hide"}
import numpy as np
x = np.array([1, 4, 9, 0])
y = np.array([1, 0, 1, 0])
print(x*0.5)
print(x+y)
print(x-y)
```
Ausgabe:
```{python, echo=FALSE}
import numpy as np
x = np.array([1, 4, 9, 0])
y = np.array([1, 0, 1, 0])
print(x*0.5)
print(x+y)
print(x-y)
```
### Neue Rechenarten
```{python, results="hide"}
import numpy as np
x = np.array([1, 4, 9, 0])
y = np.array([1, 0, 1, 0])

print(x+1)
print(x*y)
```
Ausgabe:
```{python, echo=FALSE}
import numpy as np
x = np.array([1, 4, 9, 0])
y = np.array([1, 0, 1, 0])

print(x+1)
print(x*y)
```



## Matrix mit Numpy

Matrizen werden in Numpy als eine Ansammlung von Zeilenvektoren aufgebaut!

### Beispiel

```{python, results="hide"}
import numpy as np

A = np.array([[1,2],[3,4], [5,6], [7,8]])
print( A )
print( A[0,0] )
print( A[0,1] )
```
Ausgabe: 
```{python, echo=FALSE}
import numpy as np
A = np.array([[1,2],[3,4], [5,6], [7,8]])
print( A )
print( A[0,0] )
print( A[0,1] )
```
Die Indizierung der Element funktioniert erwartungsgemäß, allerdings wird mit der Zählung bei Null begonnen!


### Shape (Dimension)

Eine Matrix hat eine Anzahl von Zeilen und Spalten. Wir verwenden wie bei Vektorek shape, um die Dimension zu erfahren 

```python
import numpy as np

A = np.array([[1,2],[3,4], [5,6], [7,8]])
print( A.shape )
```


Ausgabe:
```{python, echo=FALSE}
import numpy as np

A = np.array([[1,2],[3,4], [5,6], [7,8]])
print( A.shape )  # Ausgabe: (4,2)
```

Die Ausgabe (4,2) besagt, dass die Matrix vier Zeilen und zwei Spalten besitzt.



### Skalare Multiplikation und Addition

```{python, results="hide"}
import numpy as np

A = np.array([[1,2],[3,4], [5,6], [7,8]])
B = np.array([[10,20],[30,40], [50,60], [70,80]])
s = 2;
print (2*A)     # Mulitplikation mit einem Skalar
print (A+B)
```
Ausgabe:
```{python, echo=FALSE}
import numpy as np

A = np.array([[1,2],[3,4], [5,6], [7,8]])
B = np.array([[10,20],[30,40], [50,60], [70,80]])
s = 2;
print (2*A)     # Mulitplikation mit einem Skalar
print (A+B)
```



### Matrixmultiplikation

Die Matrixmultiplikation erfolgt über den Befehl `np.dot`. Wir berechnen als Beispiel folgendes Produkt (Immer auf die passenden shapes achten!):

$$
\mathbf{A}= \begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{bmatrix} \quad\quad\quad
\mathbf{B}= \begin{bmatrix} 1 & 0 \\ 0 & 2 \end{bmatrix}  \quad\quad\quad
\mathbf{A} \mathbf{B}= \begin{bmatrix} 1 & 4 \\ 3 & 8 \\ 5 & 12 \end{bmatrix} \quad\quad\quad
$$
Mit Numpy: `np.dot()`

```{python, results="hide"}
import numpy as np

A = np.array([[1,2],[3,4], [5,6] ])
B = np.array([[1,0],[0,2]])
AB = np.dot(A, B) 
print( AB )
```
Ausgabe:
```{python, echo=FALSE}
import numpy as np

A = np.array([[1,2],[3,4], [5,6] ])
B = np.array([[1,0],[0,2]])
AB = np.dot(A, B) 
print( AB )
```



## XXX > Einfache Funktionen

```python
import numpy as np

# Sinus
x = np.sin(0)
print( x )

# Quadrieren
x = np.square(3)
print( x )

# PI
x = np.pi
print( x )

# Eulersche Zahl
x = np.e
print( x )

# Gleichverteilt in [0,1[ 
x = np.random.random()
print(x)

# Erwartungswert 0, Standardabweichung 1
x = np.random.normal(0,1)
print(x)
```



## Vektoren 

Da Feature-Vektoren für uns eine wichtige Rolle spielen, gehen wir näher auf Vektoren in Numpy ein. 



### Erzeugung  "per Hand"

Folgende Befehle erläutern das Thema Vektoren, elementweise Addition, elementweise Multiplikation und Skalarprodukt für Vektoren. Wichtig für die Erzeugung eines Vektors ist Zeile 3.

```python
import numpy as np

y = np.array([5,6,7,8])     # Definiere Vektor y
x = np.array([1,2,3,4])     # Definiere Vektor x
print (f'x    = {x}' )      # Drucke Werte
print (f'y    = {y}' )      # Drucke y
```



### `np.ones() und np.zeros()`

`np.ones(n)` erzeugt einen Vektor der Dimension n, der nur aus Einsen besteht. Analog funktioniert `np.zeros`

```python
v = np.ones(10)
w = np.zeros(10)
```



### `np.arange`()

Mit `np.arange` erzeugen wir automatisch Strukturen, die wir häufiger brauchen. Beschäftigen Sie sich mit den Ausgaben und experimentieren sie etwas, dann wird die jeweilige Funktion recht schnell klar.

```python
import numpy as np

x = np.arange(1,2,0.1)
print( x )
print( x[2] )
print( len(x) )
print ( type(x) )
```



###  `np.linspace`()

```python
import numpy as np

x = np.linspace(0,2*np.pi,20);
print(x)
print( len(x))
```



### Elementweise Operationen

 Nachfolgendes Beispiel zeigt ausgewählte Operationen. Beachten Sie, dass sie die letzten vier Operationen so im Mathe-Unterricht nicht gelernt haben. Sie sind jedoch recht hilfreich!

```python
import numpy as np
x = np.array([1, 4, 9, 0])
y = np.array([1, 0, 1, 0])

print(x*0.5)
print(x+y)
print (x.dot(y))

print (x+1)
print(x*y)
print (np.sqrt(x))
print (np.sin(x))
```



### Übung

Berechnen Sie durch Programmbefehle $v^Tw,$ $v+w$ und $2 \cdot v$ für

$$
v = \begin{bmatrix} 1 \\ -3 \\ 2\\ \end{bmatrix} \quad \text{and} \quad w = \begin{bmatrix} 1 \\ 0 \\ 13\\ \end{bmatrix}
$$







## Zufallszahlen

Link: [https://www.w3schools.com/python/numpy/numpy\_random.asp](https://www.w3schools.com/python/numpy/numpy\_random.asp)

```python
import numpy as np

# Gleichverteilt in [0,1[, 10 Werte
ua = np.random.random(10)
print(ua)

# Erwartungswert 0, Standardabweichung 1, 10 Werte
na = np.random.normal(0,1,10)
print(na)
```









## Vertiefend



### Zeilenvektoren und Spaltenvektoren

Eigentlich sollten wir unterscheiden zwischen

- Vektor der Dimension $n$
- $1 \times n$ Matrix ("Zeilenvektor")
- $n \times 1$ Matrix ("Spaltenvektor")

In Numpy geht das auch, wie folgende Code zeigt. Wie üblich werden aber Vektoren in das entsprechende Format gebracht. (Stören sie sich bitte nicht an runden und eckigen Klammern - sie haben keine Bedeutung.)
$$
v = \begin{bmatrix} 2 \\ 2 \\ 3 \end{bmatrix} \quad\quad\quad 
vz = (-1, 2, 3)
$$

```python
import numpy as np

v  = np.array([1,2,3])          # Vektor
vz = np.array([[1,2,3]])        # 1 x 3 Matrix
vs = np.array([[1], [2], [3]])  # 3 x 1 Matrix

print(f'v  : {v}')
print(f'vz : {vs}')
print(f'vs : {vz}')

print(f'Shape v  :{v.shape}')
print(f'Shape vz :{vz.shape}')
print(f'Shape vs :{vs.shape}')
```

Wir sollten also stets überlegen, mit welchem shape wir operieren.



### Transponierung

```python
import numpy as np

A = np.array([[1,2],[3,4], [5,6], [7,8]])
AT = np.transpose(A)
print(AT)
```





