# Visualisierung zu IRIS 


## Laden des Datensatzes

Mit folgendem Programm laden wird die Iris-Daten in einen Dataframe mit dem Namen `iris_df`. Wir verwenden dazu das Paket **sklearn**. Details finden sie unter https://scikit-learn.org/stable/. Sklearn ist eine Sammlung von Basisprogrammen für Machine-Learning, die auf NumPy und Matplotlib aufbaut.
```{python, results="hide"}
import pandas as pd
from sklearn import datasets
import matplotlib.pyplot as plt

iris = datasets.load_iris()
iris_df = pd.DataFrame(iris.data)
iris_df['class']=iris.target_names[iris.target ]
iris_df.columns=['sepal_len', 'sepal_wid', 'petal_len', 'petal_wid', 'class']
```



#### Überblick verschaffen {-}

Zunächst drucken wir den Dataframe mit `print`aus. Bei einer großen Anzahl von Zeilen zeigt die Funktion nur die ersten und letzten Zeilen an.

```{python, results="hide"}
print( iris_df )
```
Ausgabe:
```{python, echo=FALSE}
print( iris_df )
```
Der Datensatz enthält also 150 Zeilen und 5 Spalten. Wir verschaffen uns nun einen Überblick  über die Datentypen:

```{python, results="hide"}
iris_df.info()
```
Ausgabe:
```{python, echo=FALSE}
iris_df.info()
```
Die ersten vier Spalten des Datensatzes  haben einen numerische Datentyp - wie wir das auch erwarten. Die Spalte  `class` hat den Datentyp `object`. Es handelt sich  konkret um Strings
^[Wir gehen nicht darauf ein, weshalb der Datentyp nicht string (`<str>`) ist. Interessierte erhalten den Datentyp über `type( iris_df.iloc[0,4] )`. ].  
Für alle Spalten  des Datensatzes wird ein `Non-Null Count` von `150 non-null` angezeigt. Das bedeutet, dass für die jeweiligen Spalten überall Werte vorhanden sind - erfreulich!

Wir schließen mit einfachen Statistiken ab und starten in die Auswertungen:
```{python, results="hide"}
iris_df.describe()
```
Ausgabe:
```{python, echo=FALSE}
iris_df.describe()
```
## Countplot (Categorical)

```{python, results="hide"}
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
sns.set_theme()

fig, ax = plt.subplots( figsize=(7,5))
ax.set_title("Iris Countplot - Anzahl nach Lilienart")
sns.countplot(data = iris_df,  x = "class")
```

## Single Numerical Feature

### Swarmplot

```{python,results="hide"}
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
sns.set_theme()

fig, ax = plt.subplots( figsize=(7,5))
ax.set_title("Iris Swarmplot - petal-width")
sns.swarmplot(data = iris_df,  x = "petal_wid")
```




### Histogramm (petal_wid)

```{python,results="hide"}
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
sns.set_theme()

fig, ax = plt.subplots( figsize=(7,5))
ax.set_title("Iris Histogram (sepal_wid)")
sns.histplot( iris_df, 
             x ="sepal_wid", 
             bins=10,  # try bins="auto" und bins=10
             kde = False)
```

### Violinplot

```{python,results="hide"}
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
sns.set_theme()

fig, ax = plt.subplots( figsize=(7,5))
ax.set_title("Iris Swarmplot - sepal-width")
sns.violinplot(data = iris_df,  x = "sepal_wid", inner="quartiles")
```

### Boxplot
```{python,results="hide"}
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
sns.set_theme()

fig, ax = plt.subplots( figsize=(7,5))
ax.set_title("Iris Swarmplot - sepal-width")
sns.boxplot(data = iris_df,  x = "sepal_wid")
```

##  Single Feature & Category

###  Swarm

```{python,results="hide"}
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
sns.set_theme()

fig, ax = plt.subplots( figsize=(7,5))
ax.set_title("Iris Swarmplot for sepal_wid")
sns.swarmplot(data = iris_df,  x = "sepal_wid", y="class")
```

###  Violin

```{python,results="hide"}
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
sns.set_theme()

fig, ax = plt.subplots( figsize=(7,5))
ax.set_title("Iris Violinplot for sepal_wid")
sns.violinplot(data = iris_df,  x = "sepal_wid", y = "class", inner="quartiles")
```

## Relationplots

```{python}
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

sns.set_theme()
sns.set_context("notebook", font_scale=1.4)
fig, ax = plt.subplots( figsize=(7,5))
ax.set_title("Iris Relationplot for sepal_wid/sepal_len")

sns.relplot(data=iris_df, x="sepal_wid", y="sepal_len", hue = "class", height=11, s = 90) # try style="class"
```


## Pairplots
```{python}
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

sns.set_theme()
sns.set_context("notebook", font_scale=1.3)
fig, ax = plt.subplots( figsize=(7,5) )
ax.set_title("Iris Pairplots")

sns.pairplot(iris_df, hue="class", diag_kind="kde", height=3)
```
